driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu:20.04
    pre_build_image: true
    command: /bin/bash
    capabilities:
      - SYS_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
  playbook: verify.yml

scenario:
  name: default
  test_sequence:
    - converge
    - verify